// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gen_proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Origin describes the source of a message
type Origin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                            // "agent", "client", "system"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                // "planner", "tester-ui"
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID or specific session identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Origin) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Origin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Origin) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Wrapper is the top-level envelope for all binary messages.
type Wrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Data type: "text", "json", "a2ui", "telemetry"
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // Serialized actual payload content
	Origin        *Origin                `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   []string               `protobuf:"bytes,7,rep,name=destination,proto3" json:"destination,omitempty"` // Array of session UUIDs. Empty means broadcast.
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Event         string                 `protobuf:"bytes,9,opt,name=event,proto3" json:"event,omitempty"`                                    // "narrative", "tool_call", "model_end", etc.
	Metadata      []byte                 `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // JSON encoded metadata (tokens, model ID)
	SimulationId  string                 `protobuf:"bytes,11,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"` // Groups messages by simulation run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Wrapper) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Wrapper) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Wrapper) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Wrapper) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Wrapper) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Wrapper) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Wrapper) GetDestination() []string {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Wrapper) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Wrapper) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Wrapper) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Wrapper) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

// BroadcastRequest allows a single client to fan-out a payload to many agents.
type BroadcastRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payload          []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	TargetSessionIds []string               `protobuf:"bytes,2,rep,name=target_session_ids,json=targetSessionIds,proto3" json:"target_session_ids,omitempty"`
	Async            bool                   `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"` // If true, return ack immediately; if false, wait for responses.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BroadcastRequest) GetTargetSessionIds() []string {
	if x != nil {
		return x.TargetSessionIds
	}
	return nil
}

func (x *BroadcastRequest) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

// BatchResponse aggregates responses from multiple agents into one message.
type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Responses     []*Wrapper             `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *BatchResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchResponse) GetResponses() []*Wrapper {
	if x != nil {
		return x.Responses
	}
	return nil
}

// ToolCallRequest is used by agents (Brain) to query or act on the state registry (Body).
type ToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ToolCallRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// ToolCallResponse is the result of a ToolCallRequest.
type ToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResponse) Reset() {
	*x = ToolCallResponse{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResponse) ProtoMessage() {}

func (x *ToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResponse.ProtoReflect.Descriptor instead.
func (*ToolCallResponse) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ToolCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A2UIAction carries a user interaction from an A2UI Button back to the
// originating agent session.
type A2UIAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`    // Target agent session UUID
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"` // Action identifier (e.g. "run_simulation")
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                         // Optional JSON context for future extensibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2UIAction) Reset() {
	*x = A2UIAction{}
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2UIAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2UIAction) ProtoMessage() {}

func (x *A2UIAction) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2UIAction.ProtoReflect.Descriptor instead.
func (*A2UIAction) Descriptor() ([]byte, []int) {
	return file_gen_proto_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *A2UIAction) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *A2UIAction) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *A2UIAction) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_gen_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_gen_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1fgen_proto/gateway/gateway.proto\x12\agateway\"K\n" +
	"\x06Origin\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xcd\x02\n" +
	"\aWrapper\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\x06origin\x18\x06 \x01(\v2\x0f.gateway.OriginR\x06origin\x12 \n" +
	"\vdestination\x18\a \x03(\tR\vdestination\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05event\x18\t \x01(\tR\x05event\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\fR\bmetadata\x12#\n" +
	"\rsimulation_id\x18\v \x01(\tR\fsimulationId\"p\n" +
	"\x10BroadcastRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12,\n" +
	"\x12target_session_ids\x18\x02 \x03(\tR\x10targetSessionIds\x12\x14\n" +
	"\x05async\x18\x03 \x01(\bR\x05async\"^\n" +
	"\rBatchResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\tresponses\x18\x02 \x03(\v2\x10.gateway.WrapperR\tresponses\"\xaf\x01\n" +
	"\x0fToolCallRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12<\n" +
	"\x06params\x18\x02 \x03(\v2$.gateway.ToolCallRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x10ToolCallResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\n" +
	"A2UIAction\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontextBAZ?github.com/GoogleCloudPlatform/race-condition/gen_proto/gatewayb\x06proto3"

var (
	file_gen_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_gen_proto_gateway_gateway_proto_rawDescData []byte
)

func file_gen_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gen_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gen_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gen_proto_gateway_gateway_proto_rawDesc), len(file_gen_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_gen_proto_gateway_gateway_proto_rawDescData
}

var file_gen_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gen_proto_gateway_gateway_proto_goTypes = []any{
	(*Origin)(nil),           // 0: gateway.Origin
	(*Wrapper)(nil),          // 1: gateway.Wrapper
	(*BroadcastRequest)(nil), // 2: gateway.BroadcastRequest
	(*BatchResponse)(nil),    // 3: gateway.BatchResponse
	(*ToolCallRequest)(nil),  // 4: gateway.ToolCallRequest
	(*ToolCallResponse)(nil), // 5: gateway.ToolCallResponse
	(*A2UIAction)(nil),       // 6: gateway.A2UIAction
	nil,                      // 7: gateway.ToolCallRequest.ParamsEntry
}
var file_gen_proto_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.Wrapper.origin:type_name -> gateway.Origin
	1, // 1: gateway.BatchResponse.responses:type_name -> gateway.Wrapper
	7, // 2: gateway.ToolCallRequest.params:type_name -> gateway.ToolCallRequest.ParamsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gen_proto_gateway_gateway_proto_init() }
func file_gen_proto_gateway_gateway_proto_init() {
	if File_gen_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gen_proto_gateway_gateway_proto_rawDesc), len(file_gen_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gen_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gen_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_gen_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gen_proto_gateway_gateway_proto = out.File
	file_gen_proto_gateway_gateway_proto_goTypes = nil
	file_gen_proto_gateway_gateway_proto_depIdxs = nil
}
